openapi: 3.0.0
info:
  title: Tagify
  version: '1.0'
  description: ''
  contact:
    name: Karol Rogoza
  license:
    name: GNU General Public License v3.0
    url: 'https://fsf.org'
servers:
  - url: 'http://localhost:5000'
paths:
  /api/auth/me:
    get:
      summary: whoami
      tags:
        - Auth
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  username:
                    type: string
                  nickname:
                    type: string
                  role:
                    type: string
                  date_created:
                    type: string
                  last_modified:
                    type: string
              examples:
                example:
                  value:
                    id: 20
                    username: user
                    nickname: BIG BOB
                    role: tagger
                    date_created: 20/12/20
                    last_modified: 21/12/21
        '401':
          description: 'Unauthorized, you need to be logged in'
      operationId: get-api-auth
      description: 'get user information (user & admin)'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
            examples:
              example:
                value:
                  username: user1
    parameters: []
  /api/auth/login:
    post:
      summary: login
      tags:
        - Auth
      responses:
        '200':
          description: OK
        '401':
          description: 'Unauthorized, wrong password or user_name'
      operationId: post-api-auth-login
      description: 'login (user & admin)'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
            examples:
              example:
                value:
                  username: user1
                  password: password
        description: user data needed for authentication
  /api/auth/logout:
    post:
      summary: logout
      tags:
        - Auth
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      operationId: post-api-auth-logout
      description: 'logout (user & admin)'
      parameters: []
      requestBody:
        content:
          application/xml:
            schema:
              type: object
              properties:
                username:
                  type: string
            examples:
              example:
                value:
                  username: user1
        description: ''
  /:
    get:
      summary: get server status
      tags: []
      responses:
        '200':
          description: 'OK, server is working'
        '404':
          description: 'server is broken :('
      operationId: get
      description: check or server is working
  '/api/admin/user/{user_id}':
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
    get:
      summary: get user by name
      tags:
        - admin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  nickname:
                    type: string
                  id:
                    type: number
                  date_created:
                    type: string
                  last_modify:
                    type: string
      operationId: get user by username
      description: Get user by username
    put:
      summary: update user data
      tags:
        - admin
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      operationId: put-user-id
      description: change user data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                password:
                  type: string
                repeat_password:
                  type: string
            examples:
              example_ user:
                value:
                  username: user123
                  nickname: user123
                  password: new_password
                  repeat_password: new_password
                  is_admin: false
              example_admin:
                value:
                  username: admin123
                  nickname: admin123
                  password: new_password
                  repeat_password: new_password
                  is_admin: true
    delete:
      summary: delete user account
      tags:
        - admin
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      operationId: delete-user-id
      description: delete user
  /api/admin/user:
    post:
      summary: create new user account
      tags:
        - admin
      responses:
        '201':
          description: 'Created, new user is created'
        '400':
          description: 'Bad Request, wrong form'
        '401':
          description: 'Unauthorized, are u admin?'
      operationId: post-api-admin-user
      description: create new user account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                nickname:
                  type: string
                password:
                  type: string
                repeat_password:
                  type: string
                is_admin:
                  type: boolean
              required:
                - username
                - nickname
                - password
                - repeat_password
                - is_admin
            examples:
              example_user:
                value:
                  username: user
                  nickname: user
                  password: password
                  repeat_password: password
                  is_admin: false
              example_admin:
                value:
                  username: admin
                  nickname: admin
                  password: password
                  repeat_password: password
                  is_admin: true
  /api/admin/users:
    get:
      summary: get all users
      tags:
        - admin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      username:
                        type: string
                      nickname:
                        type: string
                      is_admin:
                        type: boolean
                      id:
                        type: number
                  - properties:
                      username:
                        type: string
                      nickname:
                        type: string
                      is_admin:
                        type: boolean
                      id:
                        type: number
                  - properties:
                      username:
                        type: string
                      nickname:
                        type: string
                      is_admin:
                        type: boolean
                      id:
                        type: number
                type: object
        '401':
          description: Unauthorized
      operationId: get-api-admin-users
      description: get all users
  /api/user:
    parameters: []
    get:
      summary: get user data
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  nickname:
                    type: string
              examples:
                example:
                  value:
                    username: user
                    nickname: BIG BOB
        '401':
          description: Unauthorized
        '':
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  username:
                    type: string
                  nickname:
                    type: string
                  date_created:
                    type: string
                  last_modify:
                    type: string
      operationId: get-api-user-username
      description: get actual user data
    put:
      summary: change user data
      tags:
        - user
      responses: {}
      operationId: put-api-user-username
      description: change user nickname
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                '':
                  type: string
        description: ''
    delete:
      summary: delete user
      tags:
        - user
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      operationId: delete-api-user-username
      description: delete own account
  /api/albums:
    get:
      summary: get album with picture and progress
      tags:
        - album
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      album_id:
                        type: string
                      album_name:
                        type: string
                      numbler_of_photos:
                        type: number
                      number_tagged_photos:
                        type: number
                      preview_image:
                        type: string
                  - properties:
                      album_id:
                        type: string
                      album_name:
                        type: string
                      numbler_of_photos:
                        type: number
                      number_tagged_photos:
                        type: number
                      preview_image:
                        type: string
                type: object
              examples:
                example:
                  value:
                    album_id: 12
                    alum_name: cats
                    number_of_photos: 12000
                    number_tagged_photos: 7000
                    preview_image: /jhsdi/jkasdjk/cats/123
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: get-api-album
      description: |-
        get album with some data
        get album preview image with completion rate (25 albums)
    parameters: []
  '/api/user/{username}/password':
    parameters:
      - schema:
          type: string
        name: username
        in: path
        required: true
    put:
      summary: change user password
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      operationId: put-api-user-username-password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                repeat_password:
                  type: string
      tags:
        - user
  '/api/admin/album/{album_id}':
    parameters:
      - schema:
          type: string
        name: album_id
        in: path
        required: true
    put:
      summary: change album meta data
      tags:
        - admin
        - album
      responses: {}
      operationId: put-api-admin-album-album_id
    delete:
      summary: delete album
      tags:
        - admin
        - album
      responses: {}
      operationId: delete-api-admin-album-album_id
  /api/admin/albums:
    get:
      summary: get all albums
      tags:
        - admin
        - album
      responses: {}
      operationId: get-api-admin-albums
  /api/user/albums:
    get:
      summary: get all my albums
      tags:
        - album
        - user
      responses: {}
      operationId: get-api-user-albums
  '/api/user/album/{album_id}':
    parameters:
      - schema:
          type: string
        name: album_id
        in: path
        required: true
    get:
      summary: get album data (by album_id)
      tags:
        - user
        - album
      responses: {}
      operationId: get-api-user-album-album_id
    put:
      summary: edit my album data
      tags:
        - user
        - album
      responses: {}
      operationId: put-api-user-album-album_id
    delete:
      summary: delete my album
      tags:
        - user
        - album
      responses: {}
      operationId: delete-api-user-album-album_id
  /api/user/lastalbums:
    get:
      summary: get last edited albums
      tags:
        - user
        - album
      responses: {}
      operationId: get-api-user-lastalbums
  /api/album/photos:
    get:
      summary: get next 15 photos for anotation
      tags:
        - photos
        - album
      responses: {}
      operationId: get-api-album-photos
  '/api/album/{album_id}photo/{photo_id}':
    parameters:
      - schema:
          type: string
        name: photo_id
        in: path
        required: true
      - schema:
          type: string
        name: album_id
        in: path
        required: true
    post:
      summary: sent photo with anotation
      tags:
        - album
        - photos
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
      operationId: post-api-album-photo-photo_id
    put:
      summary: verify photo (second user)
      tags:
        - album
        - photos
      responses: {}
      operationId: put-api-album-photo-photo_id
    get:
      summary: ''
      operationId: get-api-album-album_id-photo-photo_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  photo_id:
                    type: number
                  actual_tag:
                    type: string
                  coordinates:
                    type: array
                    items:
                      type: number
                  verified:
                    type: boolean
                  tagged:
                    type: boolean
  /api/user/password:
    put:
      summary: change own password
      tags:
        - user
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      operationId: put-api-user-password
      description: change own password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                password_repeat:
                  type: string
  '/api/album/{album_id}':
    parameters:
      - schema:
          type: string
        name: album_id
        in: path
        required: true
    get:
      summary: get 15 preview photos of album
      tags:
        - album
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  album_id:
                    type: string
                  description:
                    type: string
                  number_of_photos:
                    type: string
                  number_tagged_photos:
                    type: string
                  album_owner_id:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string
      operationId: get-api-album-album_id
      description: get only deta without photos
  '/api/album/{album_id}/photos':
    parameters:
      - schema:
          type: string
        name: album_id
        in: path
        required: true
    get:
      summary: get next 25 photos from album (preview)
      tags:
        - album
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      tagged:
                        type: boolean
                      verified:
                        type: boolean
                      image_path:
                        type: string
                      photo_id:
                        type: number
                  - properties:
                      tagged:
                        type: boolean
                      verified:
                        type: boolean
                      image_path:
                        type: string
                      photo_id:
                        type: number
                type: object
      operationId: get-api-album-album_id-photos
      description: get preview photos form album
components:
  schemas: {}
  securitySchemes: {}
